version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: star-wars-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/15Dev.123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - star-wars-network

  app:
    build: .
    container_name: star-wars-qa-app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=15Dev.123
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./star_wars.db:/app/star_wars.db:ro
      - ./data:/app/data
    networks:
      - star-wars-network
    restart: unless-stopped

  # Serviço opcional para importar dados
  importer:
    build: .
    container_name: star-wars-importer
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=15Dev.123
    volumes:
      - ./star_wars.db:/app/star_wars.db:ro
      - ./import_to_neo4j.py:/app/import_to_neo4j.py:ro
    networks:
      - star-wars-network
    command: ["python", "import_to_neo4j.py"]
    profiles:
      - import

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  star-wars-network:
    driver: bridge 